version: "3"

services:
  node0:
    container_name: mynode0
    image: "tendermint/localnode_my"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build_my:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  node1:
    container_name: mynode1
    image: "tendermint/localnode_my"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build_my:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  node2:
    container_name: mynode2
    image: "tendermint/localnode_my"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build_my:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  node3:
    container_name: mynode3
    image: "tendermint/localnode_my"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build_my:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.9

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
